# Funding links for GitHub's Sponsor button.
# See: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: thangngh00gmailcom
buy_me_a_coffee: thangngh00z
custom:
  - https://www.paypal.com/paypalme/thangngh
